- name: Install pre-requisites tools
  hosts: my_machine
  become: true
  connection: local
  tasks:
    - name: update APT Package
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - wget
          - gnupg
          - software-properties-common
        state: present

    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp.list

    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: yes

    - name: Install kubectl
      snap:
        name: kubectl
        classic: yes
        state: present

    - name: Install Multipass
      community.general.snap:
        name: multipass
        state: present
    

